### PR TITLE
Add Angular Universal support by checking if browserSide

### LINKED ISSUE #73: Angular Universal Support
As i tried out this (really nice and helpful) library i got surprised with the fact, that Angular Universal threw an Error.
`lcoalstorage is not defined`

It seems that this library doesnt support Angular Universal. I think many would appreciate support for it.

I solved it in the meanwhile with:
```typescript
const customStorage: Storage = {
  length: 0,
  clear: function (): void {
    if (window && window.localStorage) {
      window.localStorage.clear();
      this.length = window.localStorage.length;
    }
  },
  getItem: function (key: string): string | null {
    try{
      return window.localStorage.getItem(key);
    }catch{
      return null;
    }
  },
  key: function (index: number): string | null {
    try {
      return window.localStorage.key(index);
    }catch{
      return null;
    }
  },
  removeItem: function (key: string): void {
    try {
      window.localStorage.removeItem(key);
      this.length = window.localStorage.length;
    }catch{
        return ;
      }
  },
  setItem: function (key: string, data: string): void {
    try{
      window.localStorage.setItem(key, data);
      this.length = window.localStorage.length;
    }catch{
        return ;
      }
  }
};

export function localStorageSyncReducer(reducer: ActionReducer<any>): ActionReducer<any> {
  return localStorageSync({keys: [{auth: ["token"]},{shopping_cart: ["products"]}], rehydrate: true, storage: customStorage})(reducer);
}

```

### PR DESCRIPTION
**Pull request by ebondu**
fix #73

### CODE REVIEW

**Comment by arrenv** [comment]
I have been testing your fork, however, seem to still have issues when testing server-side with Universal.

This is the error I get:

ReferenceError: localStorage is not defined
    at C:\Users\arren\dev\propxrty\node_modules\ngrx-store-localstorage\dist\index.js:193:26

**Comment by ebondu** [comment]
Did you set the ```checkStorageAvailability``` field to ```true``` in your ```LocalStorageConfig```?

**Comment by arrenv** [comment]
Thank you, @ebondu that fixed it.

On another note, is there a way to have the dist included in your package, or do you just build it each time?

**Comment by free-easy** [comment]
Which is the reason that prevents this PR to be merged?

**Comment by free-easy** [comment]
Can I do anything to accelerate this?

**Comment by bufke** [comment]
I tested this with a reasonably large angular universal project. I think this is fairly safe as it's opt in only. checkIsBrowserEnv would fail if someone polyfill'ed window. This probably fixes it for most people and removes the need to write hacky storage solutions. A unit test would be great but I don't know any good way to simulate it.

@free-easy time is the reason - let us know if you'd like to help maintain. It's time consuming because some bugs affect some people and not others and fixing one issue can break it for another. It has some test coverage but it doesn't cover every real life use case.

**Comment by free-easy** [comment]
Thank you for merging this!
Currently, I don't have enough time to help to maintain this project, but if I encounter any bugs when I use this library, I'll for sure submit PRs!

**Pull request merged**
