### PR TITLE
Set up Circle CI

### PR DESCRIPTION
**Pull request by BBlackwo**

### CODE REVIEW

**Comment by BBlackwo** [comment]
Hi Brian @btroncone, I'd like to set up Circle CI to run on pull requests, but I'd need admin access to enable it on this repo.

I tried it out on [my fork of this repo](https://github.com/BBlackwo/ngrx-store-localstorage/pull/1) and it works great.

**Comment by btroncone** [comment]
@BBlackwo After poking around for a while I can't figure out a way to give collaborators this permission. Is there something I can do to help?

**Comment by BBlackwo** [comment]
@btroncone looks like you can't grant collaborators access with [Personal user accounts](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository). It'd have to be an organisation to give others admin access.

>There is only one owner of a repository owned by a user account; this permission cannot be shared with another user account. To transfer ownership of a repository to another user, see "How to transfer a repository."

So I guess you could just enable Circle CI for this project if you have time? It's pretty easy to do. Just have to authenticate with GitHub and then enable it for the repository.

**Comment by BBlackwo** [comment]
Once you enable it, I can just change the `.circleci/config.yml` as needed.

**Comment by BBlackwo** [comment]
If you have a chance to do that, would you also be able to add an environment variable called `NPM_TOKEN` with your NPM auth token? Cause I'd like to set up a [CI job to publish to NPM](https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/), so that you don't have to manually publish.

**Comment by btroncone** [comment]
@BBlackwo I enabled circleci, please let me know if there is anything else you need me to do. I'll also look into the npm token. Thanks!

**Comment by BBlackwo** [comment]
Thank you!

**Pull request merged**
