### PR TITLE
Remove deprecated `localStorageSyncAndClean`, v9 changelog

### PR DESCRIPTION
**Pull request by BBlackwo**
- feat: remove deprecated localStorageSyncAndClean function
- update changelog and bump to version 9.0.0

Changelog updated for #142 and #135.

### CODE REVIEW

**Comment by BBlackwo** [comment]
Hey @btroncone if you're happy with this, could we get this merged and 9.0.0 released?

FYI I updated the changelog for your PRs @shahmirn and @rowandh

**Comment by btroncone** [comment]
I’ll let you make final decision on merge, as I’ve been out of the loop. But let me know as soon as you do and I’ll cut the release! 👍

**Comment by BBlackwo** [comment]
Hi @btroncone it's merged. Could you please release it?

**Comment by btroncone** [comment]
@BBlackwo This has been released, thanks! 👍

**Pull request merged**
