### PR TITLE
feat: upgrade to Angular 17

### PR DESCRIPTION
**Pull request by sf31**
## Summary
Upgrade to Angular 17

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows [our guidelines](https://github.com/btroncone/ngrx-store-localstorage/blob/master/CONTRIBUTING.md#commit):
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Current Behavior

Support to Angular 16

Issue Number:  #260

## New Behavior

Support to Angular 17

## Breaking Change?

- [X] Yes
- [ ] No

### CODE REVIEW

**Comment by h4mit** [comment]
Please merge it. I need it 😅

**Comment by travisdotwalker** [comment]
Same! Thanks!

**Comment by souravR2D2** [comment]
C'mon guys merge this.... very important

**Review by souravR2D2 — APPROVED** [review]

**Comment by sander1991** [comment]
Could you please merge this feature Branch. We also need it :).

**Comment by aymericl** [comment]
Can u merge please ? Thanks

**Comment by davidgarcial** [comment]
LGTM merge

**Review by davidgarcial — APPROVED** [review]

**Comment by nncl** [comment]
That'd be an awesome christmas miracle if someone could just merge this

**Comment by Viserius** [comment]
@BBlackwo Are you able to merge this PR?

**Comment by btroncone** [comment]
Hello all, I am not close enough to this project anymore to know whether something can be safely merged. If anyone would like permissions to admin, please let me know. I don't want this to be held up on my side anymore. Thanks!

**Comment by aymericl** [comment]
if nobody else wants admin permission, I'll take them to at least update libs.

**Comment by davidgarcial** [comment]
I can take the admin permissions im work a lot with this package

**Comment by mvanderlee** [comment]
@BBlackwo @btroncone 
This should've been released as 17.0.0 I think? 

The projects released appear to have been in lockstep with Angular released, but now 16.1.0 =>angular 17.x.
It's a minor issue but caused our build to break as `"ngrx-store-localstorage": "^16.0.0",` no longer works.

Could a 17.0.0 version be released and a note added to the release instructions?

**Comment by BBlackwo** [comment]
Thanks for the PR. Sorry for the delay on this. I had some time off, so that's why this didn't get merged for a while.

Happy for others who want to help out. There are plenty of open issues and PRs to look at :) 

@mvanderlee you're right. This commit was missing the `BREAKING CHANGE` footer to bump it to v17. I've released a v17 in #264, but I can't do anything about v16.1.0 being wrong. 

For future Angular version upgrades please make sure to add `BREAKING CHANGE` in the commit footer.

**Pull request merged**
