### PR TITLE
refactor(server): upgrade to Angular 15

### PR DESCRIPTION
**Pull request by rambo-bertelsmann**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [our guidelines](https://github.com/btroncone/ngrx-store-localstorage/blob/master/CONTRIBUTING.md#commit):
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Current Behavior

Issue Number: N/A

## Breaking Change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by BramDecuypere** [comment]
Any idea when this one will be implemented?

**Comment by Viserius** [comment]
@rambo-bertelsmann What is the status of this?

**Comment by rambo-bertelsmann** [comment]
I haven't tested it thoroughly yet, no timeline on the completion date yet. Feel free to continue on the upgrade if you want to.

**Comment by SarcevicAntonio** [comment]
Noticed the CI failed, so I updated `ng-packagr` in my pr that is based of off this one.
https://github.com/btroncone/ngrx-store-localstorage/pull/236

**Comment by BBlackwo** [comment]
Closing in favour of #237 which was just merged

**Pull request closed without merging**
