### PR TITLE
feat: upgrade to Angular 18

### PR DESCRIPTION
**Pull request by nicorivat**
Hi,

I updated the library to Angular 18 (Ngrx finally released the 18.0.0) :)

I also dumped the version to 18.0.0 to follow Angular and Ngrx versions.

Feel free to tell me if there is something else I should do / update !

### CODE REVIEW

**Comment by BBlackwo** [comment]
Hey @nicorivat, thanks for the PR!

Just needs two small changes:
1. The commit message has to have "BREAKING CHANGE" in it for the automatic versioning to bump it. E.g.
```
feat: upgrade to Angular 18

BREAKING CHANGE: Bump library version to 18 to stay in sync with Angular version
```

2. The build is failing due to the node version being put of date. Can you update the circle CI config to the latest LTS node version please. Should be v20.

Thanks.

**Comment by nicorivat** [comment]
Thx for the feedbacks ! I've made the changes ;)

**Comment by BBlackwo** [comment]
Looks good. Thanks again!

**Pull request merged**
