### PR TITLE
Oninit Object copy parameters

### PR DESCRIPTION
**Pull request by qvantor**

### CODE REVIEW

**Comment by btroncone** [comment]
Hello @qvantor,

Could you provide additional details regarding this pull request and the issues it solves? Thanks in advance, and thanks for your contribution!

**Comment by qvantor** [comment]
https://github.com/btroncone/ngrx-store-localstorage/issues/14

**Comment by bobrosoft** [comment]
@btroncone hey, is that PR still actual? Wondering if that's something important.

**Comment by wesselvdv** [comment]
@btroncone @bobrosoft 

I do believe this PR is important. If I understand it correctly, it'll make sure that if you're doing a partial local storage sync that the loading of that partial sync doesn't override your initial state, and instead merges it. I am running into this issue now.

**Comment by ernestomancebo** [comment]
hi @qvantor / @wesselvdv, just to clear this out. If you add a new key or keys to keep on sync and reload the application, if you have an initial state with any of those new keys, the already stored state swaps out the new keys. Am I right? If not, please give us details what's intended to solve.

**Comment by wesselvdv** [comment]
Hi @ernestomancebo I just tested this, but it does not seem to solve my specific issue. In that case I have no idea what this is trying to solve.

**Comment by bufke** [comment]
@qvantor I have merge access now. I'm very interested in this pull request. However it has merge conflicts and lacks tests demonstrating it's effectiveness. Is this something you'd be interested in working on?

**Comment by bufke** [comment]
I went ahead and fixed this PR up and added a test. See https://github.com/btroncone/ngrx-store-localstorage/pull/107

**Pull request closed without merging**
