### PR TITLE
Clean up, add docs for encrypt/decrypt, and node 12 bump

### PR DESCRIPTION
**Pull request by BBlackwo**
- Update build to node 12 and add `package-lock.json`
- Clean up the index (typos and unnecessary initialisation to `undefined`)
- Add `encrypt` and `decrypt` function docs

### CODE REVIEW

**Comment by BBlackwo** [comment]
Closes #101

**Comment by BBlackwo** [comment]
Is someone able to have a look at this? @btroncone or bufke?

**Comment by Jordyz96** [comment]
Is there a reason as to why the documentation hasn't been updated with the encrypt/decrypt functionality?

I had to scour the Issues section to find that there is functionality for such, although unfortunately it is not documented.

It would help so many other people.

**Comment by SilentDuskStudios** [comment]
Is there a reason as to why the documentation hasn't been updated with the encrypt/decrypt functionality?

I had to scour the Issues section to find that there is functionality for such, although unfortunately it is not documented.

It would help so many other people.

**Comment by BBlackwo** [comment]
It will be if they ever merge this PR 😕

**Comment by BBlackwo** [comment]
I guess this project is no longer maintained, given my docs PR can't even be merged in 3 months... 😞

**Comment by SilentDuskStudios** [comment]
3 months...A **stale** branch 😭 .

**Comment by btroncone** [comment]
Sorry for the crazy delay on this. Unfortunately I don't have the bandwidth to maintain this project anymore, but would be glad to add anyone as a collaborator if you want to take it over. Just let me know!

**Comment by BBlackwo** [comment]
Hi Bryan @btroncone, that's understandable. I'd be happy to help out if you add me as a collaborator.

**Comment by btroncone** [comment]
Sure, done! Thanks!

**Comment by SilentDuskStudios** [comment]
@btroncone Welcome back!
That's totally understandable, i'm just glad support will continue :)

**Pull request merged**
