### PR TITLE
Feature/mergedeep rehydrate no mutation

### PR DESCRIPTION
**Pull request by moniuch**
This is a PR that aims at solving long lasting bugs that users complained about in #110, #80, #65:
- destroy of initialState
- wrong code for partial (aka filtered) rehydration merge, which resulted in loss of parts of state
- mutability

The PR does not change existing dependencies (such as angular, ngrx store, etc), but rather **aims at fixing the current state of things and make the library safe for our users ASAP**. After the PR has been tested and approved, we can take it from there and perform upgrades as there is a couple of improvement needs, such as add `storeFreeze` in tests

The immutability, as I believe, has been achieved sufficiently by using spread operator, rather than by using a third-party library. It was tested on an app which has `storeFreeze` in place (as the last meta reducer):

`[localStorageSyncReducer, storeFreeze];`

In order to achieve the proper deep merge behavior, `lodash.merge` has been added. We can change it to `immutable.js` later, however there is a big footprint and some [tree-shakeability complaints](https://github.com/facebook/immutable-js/issues/1190) on their repo.

The PR adds two test cases for filtered scenarios, including a case where the state in save in separate chunks rather than in one combined piece.
 
Let's test it thoroughly before we merge.

### CODE REVIEW

**Comment by btroncone** [comment]
This lgtm from a cursory glance. Could someone more familiar with current project please take a look as well, thanks! @bufke

**Comment by moniuch** [comment]
@JohnKis Thanks for your valuable input. You are right that this scenario was kind of neglected and should be handled. I will try to look into solving it over the weekend.

The main purpose of this PR though is to fix the critical bugs which users suffer from. IMO it is better to proceed incrementally, ie. merge this code which I believe solves harmful bugs and then try to improve it by handling other case. Granted, the previous code might have been able to remove keys, but it had nasty bugs where the state was completely destroyed.

So the main questions are: would merging this PR be harmful to users? would it solve problems?

If we now choose to try to solve all imperfections that this code has, we will probably never move forward.

**Comment by JohnKis** [comment]
Sure, I can create it. I'm wondering whether it's worth doing after this PR got merged, otherwise the issue won't make a lot of sense in the context of the current release.

**Comment by moniuch** [comment]
@JohnKis I believe there is never too many test cases :)

**Comment by bufke** [comment]
I should have time to review this tomorrow and test it with my project.

**Comment by btroncone** [comment]
I will publish this morning, sorry for delay. 👍

**Comment by moniuch** [comment]
I regret to say that this PR only partially solves the problem.
The state slices are still getting reduced down to rehydrated state only in feature modules (don't have to be lazy loaded).

Solution:
For all non-app modules (slices) that you selectively save to local storage, you need to apply [this solution](https://github.com/btroncone/ngrx-store-localstorage/issues/65#issuecomment-419166867)

So if your config keys looks like: `[{app: [...]}, {feature1: [...]}, {feature2: [...]} ]` the you need to apply this solution in your `feature1` and `feature2` reducers.

Not sure I took the right approach, I don't have any another idea, so - **help needed**.

**Pull request merged**
