### PR TITLE
Adding support to remove state when undefined

### PR DESCRIPTION
**Pull request by ernestomancebo**
This is a proposal to add the feature required in the issue **Setting state value to undefined #19**. Also added some format in order to resolve warnings (up to 30 in index.ts file) raised by tslint on _vs code_.

### CODE REVIEW

**Comment by btroncone** [comment]
Looks good to me, thanks! 👍

**Comment by ernestomancebo** [comment]
Anytime! I'll be updating the read me file for this feature

**Comment by btroncone** [comment]
Thanks! I'll merge when ready. 👍

**Pull request merged**
